version: "3.4"
services:
  db:
    image: "mongo"
    ports:
      - "27018:27017"
      
  server:
    build: .
    ports:
      - "8080:8080"

  data:
    build:
      dockerfile: ./Dockerfile-data
    ports:
      - "8081:8080"
